### ISSUE TITLE
PR提交请求

### ISSUE THREAD

**Issue by wuhan005** [weixianlove/zy-slider#2]
大佬您好。
很感谢您写的这个双向 slider 组件解决了我的燃眉之需。
我将其用在自己的项目中时遇到了一些问题，因此对组件做了一些改进。
现提交 pull request。（这是我玩 GitHub 以来第一个 PR ⁄(⁄ ⁄•⁄ω⁄•⁄ ⁄)⁄，好紧张啊~

**Comment by weixianlove** [comment]
挺好挺好
